export const ADD_SPHERE = 'ADD_SPHERE'
export const SHUFFLE = 'SHUFFLE'
export const UNSHUFFLE = 'UNSHUFFLE'
export const RESET = 'RESET'
export const START_ANIM = 'START_ANIM'
export const STOP_ANIM = 'STOP_ANIM'
export const EASTER_EGG = 'EASTER_EGG'